### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by tkoeck** [OpenArena/gamecode#134]
Hi,

I was a great fan of Open Arena but it seems to be dead. No new downloads on the official site, problems with the resolution and frame rate (especially on Linux), ...

Is it officially dead?

**Comment by NeonKnightOA** [comment]
No, it isn't. It's undergoing a content reboot (up to 0.8.8 assets were sub-par), and manpower for that part is low. Also COVID.

So far, the parts of OA3 that can be tested are the engine, gamecode and UI3.

**Comment by The-Gig** [comment]
Also, you can join OA Discord to stay in touch with the community and ask for help.
