### ISSUE TITLE
[Classic UI] cg_weaponBarStyle issues

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#143]
While trying to document cg_weaponBarStyle, I've found some issues with this command. These shots and the test were done with the most recent nightlies. Admittedly, they take place with classic UI, but... they're still bugs, so I'm reporting them.

* `cg_weaponBarStyle 2` and `4` behave the same. The code seems to be different in both cases, but in-game they have the same effect (they draw the available weapons at the left with the same properties, no apparent difference). Likewise with `5` and `7`.
* `cg_weaponBarStyle 2`, `3` and `4` aren't drawn at the very left, obstructing some of the screen.

![cg_weaponBarStyle 2](https://i.imgur.com/vZvRbnCl.jpg "cg_weaponBarStyle 2")

![cg_weaponBarStyle 3](https://i.imgur.com/qwuKhyLl.jpg "cg_weaponBarStyle 3")

**Comment by The-Gig** [comment]
I think the difference between 5 and 7 is that with 7 the background slowly changes from blue to red as your ammo goes down.

Also, I don't know if to use -1 or 8 for "no weapon bar"... What do you think existing users would expect more?

**Comment by NeonKnightOA** [comment]
I have to admit I was hesitant to actually add the "no weapon bar" option, seeing as there's already "cg_alwaysweaponbar". And IICR there _is_ a menu option to disable it.

**Comment by The-Gig** [comment]
IIRC, cg_waysweaponbar does show it "always" (1) or "when using it" (0, default iirc). Idk if that supports "never", or if people would think about searching for it there instead of cg_weaponbarstyle.
