### ISSUE TITLE
Harvester enemy capture sound bug

### ISSUE THREAD

**Issue by Bishop-333** [OpenArena/gamecode#160]
When the enemy team capture, the "yourteamcapture" sound is played instead of the "enemycapturesound"

**Comment by The-Gig** [comment]
Accorting to an old bug report I found, the opposite happened too ("rival team score sound" played when your team captured), right?

**Comment by EddieBrrrock** [comment]
yes exactly

**Comment by NeonKnightOA** [comment]
Let me check in the code...

**Comment by NeonKnightOA** [comment]
Nightly gamecode is out. Testing is required.

https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-03-25_d12d7d6.zip

**Comment by Bishop-333** [comment]
It's fixed in the new nightly 👍

**Comment by NeonKnightOA** [comment]
Excellent!
