### ISSUE TITLE
cg_leienhancement 1 make unable to launch a map "bad cgame system trap : 112"

### ISSUE THREAD

**Issue by EddieBrrrock** [OpenArena/gamecode#162]
This problem do not occur with OA 0.8.8

**Comment by The-Gig** [comment]
I think it's leilei's new partle effects system, which uses both updated gamecode and engine. Usually gamecode improvements do not require updated binaries, but that's a rare exception.
So if you try to enable it with older gamecode, it just does not work, and if you try to enable it with updated gamecode, but old or third-party binaries, the game crashes, as the engine cannot provide the feature required by game code.
