### ISSUE TITLE
Flag status icon in CTF (lower right) is not updated when the flag is taken

### ISSUE THREAD

**Issue by Bishop-333** [OpenArena/gamecode#163]
The flag status icon need to have a vid_restart to update the icon. This problem doesn't appear in OA 0.8.8.
I tought the problem was in CG_DrawScores but after replacing the OAX CG_Drawscores byt the one of 0.8.8 the problem still isn't solved.
Can someone help ?

**Comment by NeonKnightOA** [comment]
That sounds like a classic Q3 menu bug (either cgame or q3_ui).
For OA3 the classic menu won't be used, but that doesn't mean the bug can't be fixed.

**Comment by NeonKnightOA** [comment]
Does the bug still appear in b53?

**Comment by Bishop-333** [comment]
Yes unfortunately

**Comment by NeonKnightOA** [comment]
Gotta take a look at cgame then. I'll do that the next week.

**Comment by NeonKnightOA** [comment]
Here's a link to the latest nightly build. Does the problem still happen?

https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-03-24_f0838c0.zip

**Comment by Bishop-333** [comment]
No it doesn't with this one 👍

**Comment by NeonKnightOA** [comment]
Excellent! Then it was one of the problems found on saturday.
