### ISSUE TITLE
Capturelimit affects classic single player tier campaign

### ISSUE THREAD

**Issue by leilei-** [OpenArena/gamecode#267]
^

**Comment by NeonKnightOA** [comment]
I'm reopening this because I need confirmation that it's solved.

**Comment by NeonKnightOA** [comment]
Apparently @The-Gig found the culprit in a testing. I need to confirm this is the root of the issue before I can make a fix and declare the whole thing fixed.

**Comment by The-Gig** [comment]
I guess you are referring to this I wrote on Discord:
`noticed while testing Nightly Build _2024-03-27_1c0587e.zip_:
- _At least_ in FFA and POS (g\_gametype 0 and 13), if you have fraglimit set to 0, then the "required score" in the lower right corner shows your capturelimit instead! It shouldn't. Such capturelimit isn't actually effective, your score can get above it. If you _also_ set capturelimit 0, then the hud shows no required score.`

I didn't test g_gametype 2.

**Comment by NeonKnightOA** [comment]
I saw a pattern where all FFA-based gametypes were affected by something. Today I pushed a fix in the hopes of having solved that. Should be available in tomorrow's nightly.

**Comment by NeonKnightOA** [comment]
With the latest changes to SP, this particular problem should be solved. All that remains is checking that other gametypes don't suffer from it, **but that's another issue. Not this.**
