### ISSUE TITLE
[Feature] Optional Dodging?

### ISSUE THREAD

**Issue by The-Gig** [OpenArena/gamecode#291]
Hello, just dropping here a random idea which crossed my mind. I'm not saying it's a good idea, it's just an idea.
I don't even remember whether someone already proposed it in the past or not.

_What about an optional "dodging" feature?_ Like in UT99, you could double press a direction to perform a sort of lateral jump towards that direction, in order to quickly evade an incoming attack.

I can imagine a way younger me thinking "Oh, cool!" when UT99 tutorial told me about that feature. I have to admit I don't remember how often I actually used it in-game, though!

It's years I don't play UT99, so I don't remember whether it has got a cooldown time or how it works when you are already moving at fast speed... And speed in OA can become very high.... Maybe we should only allow that if your horizontal speed is slower or equal to a certain percentage of g_speed (80%? 100%? 120% 150%? 200%? IDK)? Or maybe after a certain percentage of g_speed, the resulting movement should become diagonal? I don't know.

By the way, I'm just asking for the simple "dodging" feature, _not_ for other advanced stuff like sliding, wall jumping, double jumping, wall running or else. I remember a few years ago I tried the -unfortunately unfinished- Unreal Tournament reboot (https://en.wikipedia.org/wiki/Unreal_Tournament_(cancelled_video_game)), and _I had an hard time trying to memorize all the advanced controls_. I'm not 20 anymore...
However, while dodging might be the only thing I could be able to handle comfortably, I guess it might be like g_advancedControls 1 as a bitfield so one might theoretically add other advanced movement features in the future and enable/disable them individually.

I repeat, _this is just a random idea._ I don't know whether it might be good or not. The only thing I know for sure is that I would want it as _optional_, as it adds a mechanic that could change the way the game is played and how some maps are meant to be played.

One big potential issue one should consider before adding new movement features would be characters animations. In the case of dodging, I _guess_ the usual jump animations may fit.

**Comment by NeonKnightOA** [comment]
Nope. This is straight NOTTODO.

**Comment by NeonKnightOA** [comment]
As much as a fan of the Unreal series that I am, I'm not going to do this, neither optionally nor forced.

THIS is straight NOTTODO.
