### ISSUE TITLE
[Feature] Tell players about missing objective entities

### ISSUE THREAD

**Issue by The-Gig** [OpenArena/gamecode#299]
The idea is this: checking whether a map is lacking _required_ entities and _clearly_ inform players that the current gametype cannot be played there, like writing "Neutral flag missing, unable to play Oneflag mode in this map!" in the middle of the screen. So people will stop running around the whole map searching for something that isn't there because the mapper forgot to add it or because the server admin "disabled" it.
Maybe a good "reminder" for map authors, too.

_IIRC_, there _are_ a few warnings _in console_ in a few gametypes (something similar to "Warning: Oneflag without white flag", I don't remember exactly), but _I fear they are incomplete_ and I'm unsure whether they are shown in players' console, server console or both (_should_ be both, I guess). They have the advantage of being able to handle multiple missing entities by just printing a couple of lines in console, but aren't very noticeable. I think one might kepp _both_ the console warnings and a big message for players (existing console warnings should be checked and completed).

About how to manage multiple missing entities in the middle of the screen message, I'm not sure. Just naming the first one (like it says you miss the red flag, then you recompile the map with the white flag and then it says you miss the blue one)? Or just a generic "Required objective entities missing, unable to play \<gametypename\> in this map!"?

To sum up, if I'm not mistaken:
- Gametype 4 (ctf) should warn in case of missing red or blue flags.
- Gametype 5 (oneflag) should warn in case of missing red/blue/neutral flags.
- Gametype 6 (overload) should warn in case of missing red/blue obelisks.
- Gametype 7 (harvester) should warn in case of missing red/blue/neutral obelisks. If _only_ neutral obelisk is missing, the message should be something like "Neutral oblisk is missing. It is still possible to play in this map by enabling g_harvesterFromBodies." (which however isn't something players can do online, unless server admin created Custom Votes for that).
- Should Gametype 9 (eCTF) "warn big" in case of missing red or blue flags, or only "warn small"? You can still play and win it like classic Elimination by just fragging the other team members, although you see messages like "RED flag has return" despite being no flag. But again, if people search for flags around the map, they may search forever. So, I don't know.
- Gametype 11 (DoubleDom) should warn in case of missing red/blue flags.
- Gametype 12 (Dom) should warn in caso of missing Dom points.
- Gametype 13 (Pos) probably doesn't need to warn anything, as it automatically uses neutral flag, dom points or player spawn points depending from what it finds available.

**Comment by NeonKnightOA** [comment]
There's a function that checks for the key objectives in game. It returns to console what entities are missing, and in b53.2 it'll also include Possession and Domination.

I might have to figure out how to make that message happen.

**Comment by The-Gig** [comment]
Just for the record, I just tried CTF in nigthly build [2024-03-27_1c0587e.zip](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-03-27_1c0587e.zip) and the console didn't warn me about wrackdm17 not having red and blue flags.
