### ISSUE TITLE
[OAX b53] Bot chat problem

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#300]
As described by @The-Gig in the OA Discord:

> I was doing one test in Elimination mode and a bot, MAjor, my teammate, said in team chat "I'm defending the .". I had just fired a few shots towards her, but maybe it was just a coincidence, as in the following rounds I tried shooting at her again and she said nothing.

Possible culprits: the bot reporting feature in ai_cmds.c

**Comment by NeonKnightOA** [comment]
I need to know one thing @The-Gig : does this happen with other nightly builds? I.E. one prior to March 14, for example.

**Comment by The-Gig** [comment]
I'm sorry, I don't know. It just a thing that I randomly noticed once. Usually, I don't care too much about what bots say....

**Comment by NeonKnightOA** [comment]
In the changes I made the bots should report what happens. And that is clearly a bug. I couldn't find the source of the bug however.

**Comment by The-Gig** [comment]
Just for the record, I just played Elimination with [2024-04-01_6f52109.zip](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-04-01_6f52109.zip) nitghtly build and my teammate Grunt said the same.

**Comment by NeonKnightOA** [comment]
The individual bots themselves aren't the problem.

I'm wondering if the problem is located in either match.c or the bot code. I have to revert some of the DD/DOM bot code due to differences between match.c and match.h. And I'm not allowed to add the match.c in 0.8.8 due to certain... "impurities"... found there.
