### ISSUE TITLE
[OAX b53] Overload obelisk and base rendering between matches

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#301]
As reported by @The-Gig in the forums

> When g_obeliskRespawnDelay value <> 10, [the rendering has issues]. Steps to reproduce: devmap a map in g_gametype 6, give all, destroy the obelisk. Do tests with different values.
> * With the cvar set to 5 you can see the obelisk immediately re-appears without the "growing crystal" animation, although it isn't possible to damage it yet (The problem is you see the obelisk there, while it shouldn't be there yet).
> * With 6 you can see the animation play very fast, ending before you can actually start damaging the obelisk again. (The problem is you see the obelisk there, while it shouldn't be there yet)
> * With 15 or 20, the animation plays slowly, which is not a problem, the problem is that at the middle of the animation it "skips" the second half of it and suddenly passes to show the complete crystal (that you can damage), which isn't very nice to see.

Possible culprits:
* This sounds like a regression. Maybe a comparison with the original TA code is in order.

**Comment by NeonKnightOA** [comment]
FWIW for the moment I've added a "New Round" message for the gamemode.

**Comment by NeonKnightOA** [comment]
I need to know in which situation the bug is triggered and if it happens with these releases:

- [Last nightly](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/)
- [b53](https://github.com/OpenArena/gamecode/releases/tag/oaxB53-r2)
- [Last 2023 nightly](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2023-05-30_905b539_2018-11-19_c719649_m.zip)
- [b52](https://github.com/OpenArena/gamecode/releases/tag/oaxB52)
- [First nightly](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2018-12-01_d967ac858bb7033ea06390b6a2977800f65a45ed.zip)
- 0.8.8
- And for this particular issue, Team Arena itself. In both ioq3 and vanilla TA.

**Comment by The-Gig** [comment]
> FWIW for the moment I've added a "New Round" message for the gamemode.

Just for the record, for future reference:
I think this has been reverted, as Overload doesn't have "rounds". While one obelisk has been destroyed, the other one can still be attacked and destroyed as well.
