### ISSUE TITLE
[Feature] "Advanced Options" menu for Skirmish/Create Server in Classic UI

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#302]
This one I'll add so we can declutter the options page, as OA now has plenty of options and there isn't space for everything. Only score, time, and round time limits will remain. Everything else will be moved to this screen.

What will it contain?
- Enable/Disable Grappling Hook
- Weapon Rulesets
- Physics Rulesets
- Vampire mode
- Regeneration mode
- Gametype-specific cvars

**Comment by The-Gig** [comment]
Other possible options one might _evaluate_:
- catch up
- physics: speed, knockback, gravityModifier
- quad factor, damage modifier
- spawn protection, force respawn time, respawning in waves.
- weapon respawn time (tdm has got its own cvar)
- delag hitscan
- dmflags (bitfield, their own page?)
- videoflags (bitfield)
- warmup
- com_blood
- disabling items (their own page)

I'm NOT saying all of them are required in the UI, I'm just listing possible settings which customize matches!

I suppose one should also keep in mind the Ui doesn't suggest what's the default value of settings, in case one may want to restore something to standard... Just to say that maybe cvars hard to recognize/restore to default might be omitted.

For more info: <https://antifandom.com/OpenArena/wiki/Special_game_options>

Also wondering, it is possible to make settings pages with two columns? Create server page has got two -sort of-...
