### ISSUE TITLE
[Feature] Add statusbar texts for Audio, Display and Video

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#303]
This one is self-explaantory and I'm leaving this as an open issue more as a reminder to do this before the release of b53.2 than anything else.

**Comment by The-Gig** [comment]
Mouseover hints?
I'd also mention in Player menu something indicating that che colors you choose control the colors of your own railgun traces 
(depending from cg_oldrail value, either the beam and the spiral, or the beam and the disks).

**Comment by NeonKnightOA** [comment]
Tomorrow I'll tackle this.
