### ISSUE TITLE
[Bug] "Death message output" not stored

### ISSUE THREAD

**Issue by The-Gig** [OpenArena/gamecode#328]
Tested with [2024-04-01_6f52109.zip](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-04-01_6f52109.zip) nightly build.

- Enter Setup -> Hud 
- Change "Death message output" value.
- Exit the page
- Come back there
- "Death message output" shows "Only console text" instead of the option you chose.

**Comment by NeonKnightOA** [comment]
I'll try to tackle this during the weekend.

**Comment by NeonKnightOA** [comment]
Found out the error. And it also affected `cg_weaponBarStyle`.
