### ISSUE TITLE
[Feature] Show both long and short mapname in the menus

### ISSUE THREAD

**Issue by The-Gig** [OpenArena/gamecode#333]
This regards both Classic UI and UI3.

At the moment, Classic UI menus only show the _short_ mapname (BSP file name), while UI3 shows only the _long_ filename (from the .arena file, if available). I think that for a better experience, players should somehow be informed of both.
Note: Classic UI actually shows both names in Single Player Deathmatch "unlock tiers" mode, but only the short one in Skirmish or Server Create mode.

Maybe an on/off flag to switch between the two views? A mouseover hint so when you are over the name or the levelshot of the map, you can read the other one somewhere in the page? (Maybe previous/next page might be moved to the edge to make room?) Else?

**Comment by NeonKnightOA** [comment]
First I'd like to de-overcrowd the menus before such a thing can be done.
