### ISSUE TITLE
[Brainstorming OAX b53.2 dev] Classic UI description texts for Display, Audio and Video.

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#337]
In #336 statusbar texts for Display, Audio and Video were implemented.

**HOWEVER** I'm not sold on my own descriptions for Display and Audio, and I cannot think of good description texts for Video that fit the following limits:

* No more than 96 characters.
* No more than 48 characters per line.

So, thread is open for suggestions.

**Comment by The-Gig** [comment]
Perhaps?

Lighting (r_vertexLight 0/1):
_Servers often enforce Lightmap (high quality),
turning off your Vertex (low quality) setting._

Auto Vertex Light (cg_autoVertex 0/1):
_Automatically swithes to Vertex (low quality)
light mode whenever a server allows its usage._

(Note: writing this while walking due to lack of spare time, I stepped on a poo... I like dogs, I don't like uncivilized owners).

**Comment by The-Gig** [comment]
Graphic settings:
Choose a pre-set aiming for either quality or
performance or change individual settings.

GL Driver:
Default is the right value in most cases.
Voodoo refers to old 3dfx video cards.

GL Extensions:
Should be turned on. Turning off may help
compatibility with some very old video cards.

Aspect ratio:
Choose a monitor aspect ratio before choosing
a screen resolution.

Screen Resolution:
Higher resolutions bring higher image quality
at the expense of performance.

Enable Fullescreen:
Cycle between Fullscreen and Windowed modes.

Lightning mode: see previous message.

Flares:
Glow/Lens flare effects. Nice, but in some maps
may be a distraction or cause framerate drops.

Bloom:
Glowing effects on some light sources and items.
Can have a noticeable impact on performances.

Dynamic Lights:
Allow shots, explosions, flying rockets etc. to
light part of the arena. Doesn't work in Vertex.

Geometric Detail:
Affects smoothness of curved surfaces and the
distance where low polycount 3D models are used.

Texture Detail:
Move to the right for better looking textures.
Moving to left may improve performances a bit.

Texture quality:
Set to 32 bit for best quality. Bloom effect
works only if this is set to 32 bit.

Texture Filter:
Choose Bilinear for best perfomance or
Trilinear for best quality.

Anisotropy:
Higher values allow textures to keep their
quality at longer distances.

Note: Looking at some documentation, it looks like the GUI allows to select up to 8x, but the CVAR should also support r_ext_max_anisotropy 16. Maybe 16x should be added to the GUI, after a little bit of testing? I took some screenshots and seen the texture quality being better at long distances with higher values, but I need to took the screenshots again at higher resolution to better distinguish between 8 and 16.

[Partially OT]: In Game Server page, I think it should be "framerate dependEnt", not "dependAnt", right?
