### ISSUE TITLE
[OAX B53.2] Error loading file match.c

### ISSUE THREAD

**Issue by The-Gig** [OpenArena/gamecode#341]
OAX B53.2: I just started the mod, loaded a map and scrolled back the console history.
I noticed this red "Error: file match.c, line 143: expected a number, found MSG_TAKEA".
![immagine](https://github.com/OpenArena/gamecode/assets/23258514/49b63b3d-1029-43e8-b8ca-5f0e84a365e4)

Tried doing the same with a nightly build from a few days before (_probably_ [2024-04-02_e2f919f.zip](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-04-02_e2f919f.zip)) and match.c was loaded correctly there.

I don't know, which kind of problems should I expect to be related with this error?

**Comment by NeonKnightOA** [comment]
match.c is a file from the OA data (it's present in pak0.pk3 IICR).

I'm not allowed to include that version into OAX because there were some... questionable things found there. And leilei has the OA3 version, which we cannot access. 🤷‍♂️

**Comment by leilei-** [comment]
just revert the header's renames....

**Comment by leilei-** [comment]
Did a quick fix that should nail this error 
https://github.com/OpenArena/gamecode/commit/82f680c9281ff35627a30dbf06c747430fc4a088
