### ISSUE TITLE
Request: VR Port to Meta Quest

### ISSUE THREAD

**Issue by neitey** [OpenArena/gamecode#345]
Hi, 
we would like to bring OpenArena to VR using the vr fork of Ioquake3, Quake3quest.
We would release the source code and it will be free of charge like it is obligated under the licence.

Any onbjections or notes on this?

Tried to contact members of the OA team on moddb, the official site and thru email too.

cheers.

**Comment by The-Gig** [comment]
GPL license obligates to publish the source code, under the same license, but you aren't _obligated_ to distribute the final "out of the box" package free of charge _IIRC_ (commercial use is allowed iirc). OpenArena assets are GPLv2+ too.
This said, being free of charge surely fits OpenArena better.

If you are interested, the official OpenArena Discord link is https://discord.gg/n3dTmzM

**Comment by leilei-** [comment]
not interested
